dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements-dev.txt
jobs:
  include:
    - stage: test
      script: make tests
      if: pull_request IS true
    - stage: publish-preview
      name: publish to test.pypi.org
      script: make preview-deployment
      if: pull_request IS true
deploy:
  - provider: pypi
    user: captain-kark
    password: "$pypi_password"
    on:
      tags: true
      branch: master
