dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements-dev.txt
jobs:
  include:
    - stage: test
      script: make lint
      name: pylint
    - script: make mypy
      name: mypy
    - script: make bandit
      name: bandit
    - script: make ftests
      name: pytest functional tests
    - stage: publish-preview
      name: publish to test.pypi.org
      script: make preview-deployment
after_success:
  - python setup.py egg_info --tag-build=-"$TRAVIS_PULL_REQUEST_SHA"
  - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
before_deploy:
  - python setup.py egg_info --tag-build=-${TRAVIS_TAG#*v}
deploy:
  - provider: pypi
    user: captain-kark
    password: "$pypi_password"
    on:
      tags: true
