dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements-dev.txt
jobs:
  include:
    - stage: test
      if: type = pull_request
      script: make tests
    - stage: publish-preview
      name: publish to test.pypi.org
      if: type = pull_request
      install:
        - pip install -r requirements-publish.txt
      script: make preview-deployment
    - stage: publish
      if: type = push AND tag IS present
      install:
        - pip install -r requirements-publish.txt
      script: make deployment
