dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements-dev.txt
jobs:
  include:
    - stage: test
      script: make tests
    - stage: publish-preview
      name: publish to test.pypi.org
      script: make preview-deployment
before_deploy:
  - python setup.py sdist
branches:
  only: master
deploy:
  - provider: pypi
    user: captain-kark
    password: "$pypi_password"
    on:
      tags: true
      condition: pull_request IS false
